#!/bin/bash

PROJECT_DIR="$HOME/code_for_zhuang"

mkdir -p "$PROJECT_DIR/models"
mkdir -p "$PROJECT_DIR/logs_cluster"

cd "$PROJECT_DIR"

NETWORK_VERSION=11
ENV_VERSION=9
MODEL_VERSION=2
NUM_EPISODES=10000
VARIANT=0
SEED=777
ENCODER_PATH="./autoencoder/autoencoder_models/encoder_env9_variant0_v1.pt"
FREEZE_ENCODER=1

sbatch --job-name="DQN_v${NETWORK_VERSION}.${ENV_VERSION}.${MODEL_VERSION}_variant_${VARIANT}" \
  --export=ALL,PROJECT_DIR="${PROJECT_DIR}",NETWORK_VERSION="${NETWORK_VERSION}",ENV_VERSION="${ENV_VERSION}",MODEL_VERSION="${MODEL_VERSION}",NUM_EPISODES="${NUM_EPISODES}",VARIANT="${VARIANT}",SEED="${SEED}",ENCODER_PATH="${ENCODER_PATH}",FREEZE_ENCODER="${FREEZE_ENCODER}" \
  "${PROJECT_DIR}/cluster/run_bash_GPU.sbatch"









