#!/bin/bash

PROJECT_DIR="$HOME/code_for_zhuang"

mkdir -p "$PROJECT_DIR/models"
mkdir -p "$PROJECT_DIR/logs_cluster"

cd "$PROJECT_DIR"

NETWORK_VERSION="v9h"
ENV_VERSION="9h"
MODEL_VERSION=17
NUM_EPISODES=30000
VARIANT=0
SEED=777

sbatch --job-name="DQN_${NETWORK_VERSION}.${ENV_VERSION}.${MODEL_VERSION}_variant_${VARIANT}" \
  --export=ALL,PROJECT_DIR="${PROJECT_DIR}",NETWORK_VERSION="${NETWORK_VERSION}",ENV_VERSION="${ENV_VERSION}",MODEL_VERSION="${MODEL_VERSION}",NUM_EPISODES="${NUM_EPISODES}",VARIANT="${VARIANT}",SEED="${SEED}" \
  "${PROJECT_DIR}/cluster/run_bash_GPU.sbatch"
