#!/bin/bash

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

NETWORK_VERSION=8
ENV_VERSION=5
MODEL_VERSION=1
NUM_EPISODES=30000
VARIANT=0
SEED=777

sbatch --job-name="DQN_v${NETWORK_VERSION}.${ENV_VERSION}.${MODEL_VERSION}_variant_${VARIANT}" \
  --export=ALL,PROJECT_DIR="${PROJECT_DIR}",NETWORK_VERSION="${NETWORK_VERSION}",ENV_VERSION="${ENV_VERSION}",MODEL_VERSION="${MODEL_VERSION}",NUM_EPISODES="${NUM_EPISODES}",VARIANT="${VARIANT}",SEED="${SEED}" \
  "${PROJECT_DIR}/cluster/run_bash_GPU.sbatch"











